# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_9tYRd4NhFJIhc0dDGRe77PpBjl9lzR1
"""

import numpy as np
import matplotlib.pyplot as plt
from skimage import io, color, transform

def load_image(image_path = "./images/Lenna.png"):
    image = io.imread(image_path)
    image = color.rgb2gray(image)
    image = transform.resize(image, (256,256), anti_aliasing=True)
    image = np.array(image) / 255.0
    u = np.zeros_like(image, dtype=np.float64)
    u[1:-1, 1:-1] = image[1:-1,1:-1]
    return image, u

def jacobi(u, max_iter=20, tol=1e-2):
    height, width = u.shape
    converg = []
    u = u.copy()
    for k in range(max_iter):
        u_new = np.copy(u)
        for i in range(1, height -1):
            for j in range(1, width -1):
                u_new[i, j] = 0.25 * (u[i+1, j] + u[i-1, j] + u[i, j+1] + u[i, j-1])

        # Check for convergence
        diff = np.linalg.norm(u_new - u) / np.linalg.norm(u)
        converg.append(diff)
        if diff < tol:
            print(f"Jacobi converged after {k + 1} iterations")
            break
        u = np.copy(u_new)
    return u, converg

def gauss_seidel(u, max_iter=20, tol=1e-2):
    height, width = u.shape
    converg = []
    u = u.copy()
    for k in range(max_iter):
        u_old = np.copy(u)
        for i in range(1, height - 1):
            for j in range(1, width- 1):
                u[i, j] = 0.25 * (u[i+1, j] + u[i-1, j] + u[i, j+1] + u[i, j-1])

        # Check for convergence
        diff = np.linalg.norm(u - u_old) / np.linalg.norm(u_old)
        converg.append(diff)
        if diff < tol:
            print(f"Gauss-Seidel converged after {k + 1} iterations")
            break
    return u, converg

def detect_edge(image, u, threshold=1):
    edge = np.abs(image-u)
    # scaling
    if edge.max() > 0:
        return ((edge / edge.max()) * 255).astype(np.uint8)
    else:
        return np.zeros_like(image, dtype=np.float64)

def plot_results(image,u_jacobi, jacobi_edges, u_gauss_seidel, gauss_seidel_edges):
  fig, axes = plt.subplots(2, 3, figsize=(18, 6*2))
  # Display original image

  axes[0, 0].imshow(image, cmap="gray")
  axes[0, 0].set_title("Original Gray Image")
  axes[0, 0].axis("off")

  # Display edge detected image
  axes[0, 1].imshow(u_jacobi, cmap="gray")
  axes[0, 1].set_title(f"Jacobi Smooth Image.")
  axes[0, 1].axis("off")

  # Display smoothed image
  axes[0, 2].imshow(jacobi_edges, cmap="gray")
  axes[0, 2].set_title(f"Jacobi Detected Edges")
  axes[0, 2].axis("off")

  axes[1, 0].imshow(image, cmap="gray")
  axes[1, 0].set_title("Original Gray Image")
  axes[1, 0].axis("off")

  # Display edge detected image
  axes[1, 1].imshow(u_gauss_seidel, cmap="gray")
  axes[1, 1].set_title(f"Gauss Seidel Image.")
  axes[1, 1].axis("off")

  # Display smoothed image
  axes[1, 2].imshow(gauss_seidel_edges, cmap="gray")
  axes[1, 2].set_title(f"Gauss Seidel Detected Edges")
  axes[1, 2].axis("off")


  plt.tight_layout()
  plt.suptitle("Edge Detection Results", fontsize=16)
  plt.subplots_adjust(top=0.85)
  plt.show()

def plot_convergence(jacobi_converg, gauss_converg):
    plt.figure(figsize=(10, 6))
    plt.semilogy(jacobi_converg, label="Jacobi", marker='o', alpha=0.7)
    plt.semilogy(gauss_converg, label="Gauss-Seidel", marker='o', alpha=0.7)
    plt.xlabel("Iteration")
    plt.ylabel("Error (log scale)")
    plt.title("Convergence History")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

"""## Test"""

image_path = "https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png"
image, u = load_image(image_path)
u_jacobi, jacobi_converg = jacobi(u) # there is a default threshold of 10^-6 applied here
#if even if you dont specify. same for the gauss below
u_gauss_seidel, gauss_converg = gauss_seidel(u)
jacobi_edges = detect_edge(image, u_jacobi)
gauss_seidel_edges = detect_edge(image, u_gauss_seidel)

plot_results(image,u_jacobi, jacobi_edges, u_gauss_seidel, gauss_seidel_edges)

plot_convergence(jacobi_converg, gauss_converg)

